env:
 - GHCVER=7.0.1 CABALINSTALLVER=1.16
 - GHCVER=7.0.2 CABALINSTALLVER=1.16
 - GHCVER=7.0.3 CABALINSTALLVER=1.16
 - GHCVER=7.0.4 CABALINSTALLVER=1.16
 - GHCVER=7.2.1 CABALINSTALLVER=1.18
 - GHCVER=7.2.2 CABALINSTALLVER=1.18
 - GHCVER=7.4.1 CABALINSTALLVER=1.18
 - GHCVER=7.4.2 CABALINSTALLVER=1.18
 - GHCVER=7.6.1 CABALINSTALLVER=1.18
 - GHCVER=7.6.2 CABALINSTALLVER=1.18
 - GHCVER=7.6.3 CABALINSTALLVER=1.18

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-$CABALINSTALLVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-$CABALINSTALLVER update
 - cabal-$CABALINSTALLVER install --only-dependencies
 - ghc --version

script:
 - cabal-$CABALINSTALLVER configure -v2
 - cabal-$CABALINSTALLVER build -v2
 - cabal-$CABALINSTALLVER check
 - cabal-$CABALINSTALLVER sdist
# The following scriptlet checks that the resulting source distribution can be built & installed
 - export SRC_TGZ=$(cabal-$CABALINSTALLVER info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal-$CABALINSTALLVER install "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi
